---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/jpeer264/continuous-delivery-assignments.git"

jobs:
- name: commit-stage
  plan:
  - get: git-repository
    trigger: true
  - task: run-tests
    file: git-repository/concourse/ci/commit_build.yml
